kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  name: apicast-raphael-lab-apicast-production
  uid: 9c1d855c-05a7-44b3-a585-64fe71a59eb7
  namespace: raphael-lab
  labels:
    app: apicast
    threescale_component: apicast
spec:
  replicas: 2
  template:
    metadata:
      labels:
        deployment: apicast-raphael-lab-apicast-production
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
