kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  resourceVersion: '9866734'
  name: apicast-raphael-lab-apicast-production
  uid: 9c1d855c-05a7-44b3-a585-64fe71a59eb7
  creationTimestamp: '2022-06-24T20:00:08Z'
  generation: 1
  managedFields:
    - manager: manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-06-24T20:00:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:threescale_component': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"541cb68f-b560-46ce-adb7-1e39352259ea"}': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:apicast.apps.3scale.net/admin-portal-secret-resource-version': {}
                'f:prometheus.io/port': {}
                'f:prometheus.io/scrape': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"apicast-raphael-lab-apicast-production"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    'k:{"name":"APICAST_WORKERS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"APICAST_CONFIGURATION_CACHE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"APICAST_CONFIGURATION_LOADER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"APICAST_EXTENDED_METRICS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"APICAST_OIDC_LOG_LEVEL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"APICAST_LOG_LEVEL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"APICAST_PATH_ROUTING"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"THREESCALE_DEPLOYMENT_ENV"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"THREESCALE_PORTAL_ENDPOINT"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"OPENSSL_VERIFY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8090,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":9421,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:serviceAccount': {}
              'f:serviceAccountName': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-06-24T20:00:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
            'k:{"type":"Progressing"}':
              'f:message': {}
              'f:reason': {}
          'f:readyReplicas': {}
  namespace: raphael-lab
  ownerReferences:
    - apiVersion: apps.3scale.net/v1alpha1
      kind: APIcast
      name: raphael-lab-apicast-production
      uid: 541cb68f-b560-46ce-adb7-1e39352259ea
      controller: true
  labels:
    app: apicast
    threescale_component: apicast
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: apicast-raphael-lab-apicast-production
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: apicast-raphael-lab-apicast-production
      annotations:
        apicast.apps.3scale.net/admin-portal-secret-resource-version: '9547052'
        prometheus.io/port: '9421'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 128Mi
            requests:
              cpu: 500m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /status/ready
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: apicast-raphael-lab-apicast-production
          livenessProbe:
            httpGet:
              path: /status/live
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: THREESCALE_PORTAL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: 3scaleportal-production
                  key: AdminPortalURL
            - name: THREESCALE_DEPLOYMENT_ENV
              value: production
            - name: APICAST_CONFIGURATION_LOADER
              value: boot
            - name: APICAST_LOG_LEVEL
              value: info
            - name: APICAST_PATH_ROUTING
              value: 'true'
            - name: APICAST_CONFIGURATION_CACHE
              value: '60'
            - name: OPENSSL_VERIFY
              value: 'false'
            - name: APICAST_OIDC_LOG_LEVEL
              value: info
            - name: APICAST_WORKERS
              value: '2'
            - name: TZ
              value: America/Sao_Paulo
            - name: APICAST_EXTENDED_METRICS
              value: 'true'
          ports:
            - name: proxy
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8090
              protocol: TCP
            - name: metrics
              containerPort: 9421
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            registry.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:f0e9f64c353fdbee3bf7ec0eaf070c3b75330ef659a881ec4ebc874ba584d085
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
