apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: apicast-operator
  namespace: lab-app
spec:
  channel: threescale-2.11
  installPlanApproval: Automatic
  name: apicast-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: apicast-operator.v0.5.3
